# Generated by Django 6.0.4 on 2026-04-17 15:54

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('WAVE', 'Wave Money'), ('TRUE', 'True Money'), ('BANK', 'Bank')], max_length=10)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('transfer_com', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cash_out_com', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cash_in_com', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('inter_cash_out_com', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['provider', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.branch')),
            ],
            options={
                'ordering': ['account_name'],
                'unique_together': {('branch', 'account_name')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounting.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_extra_transfer', models.BooleanField(default=False)),
                ('is_zero_commission', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.branch')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_tx_banks', to='accounting.chartofaccount')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_tx_cash', to='accounting.chartofaccount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TrueMoneyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('provider_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('transfer_com', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cash_out_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cash_out_com', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('inter_cash_out_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('inter_cash_out_com', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('agent_card_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_agent_cards', to='accounting.chartofaccount')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.branch')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cash_accounts', to='accounting.chartofaccount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('picture', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounting.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaveTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('provider_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('transfer_com', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cash_out_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cash_out_com', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('cash_in_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cash_in_com', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('agent_card_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_agent_cards', to='accounting.chartofaccount')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.branch')),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_cash_accounts', to='accounting.chartofaccount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('journal_batch', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('account_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.chartofaccount')),
                ('bank_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='accounting.banktransaction')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounting.branch')),
                ('true_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='accounting.truemoneytransaction')),
                ('wave_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals', to='accounting.wavetransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
