# Generated by Django 6.0.4 on 2026-04-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='chartofaccount',
            old_name='current_balance',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='chartofaccount',
            old_name='account_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccount',
            unique_together={('branch', 'name')},
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_type',
            field=models.CharField(choices=[('WavePartner', 'WavePartner'), ('TruePartner', 'TruePartner'), ('Bank', 'Bank'), ('Cash', 'Cash'), ('Expense', 'Expense'), ('Income', 'Income'), ('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity')], db_index=True, max_length=50),
        ),
    ]
