# Generated by Django 6.0.4 on 2026-04-17 17:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_chartofaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionsetting',
            name='cash_in_com',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='commissionsetting',
            name='cash_out_com',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='commissionsetting',
            name='inter_cash_out_com',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='commissionsetting',
            name='transfer_com',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15),
        ),
    ]
