# Generated by Django 6.0.4 on 2026-04-17 17:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_commissionsetting_cash_in_com_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='primary_category',
            field=models.CharField(default='Asset', max_length=50),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='sub_category',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
